name: 'Deploy'
description: 'Deploy action'
inputs:
  namespace:  # id of input
    description: 'Who to greet'
    required: true
    default: 'default'
  chartName:  # id of input
    description: 'Who to greet'
    required: true
  chartVersion:  # id of input
    description: 'Who to greet'
    required: true
  releaseName:  # id of input
    description: 'Who to greet'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
