---
image:
  repository: ghcr.io/overlordtm/data-api

ingressroute:
  enabled: true
  rule: Host(`api-stage.sledilnik.org`)
  certResolver: letsencrypt

# this will be env variables in container
configmap:
  data: []
    # TESTVAR: testvar

fullnameOverride: data-api